//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct CPSProcessSerNum {
    unsigned int hi;
    unsigned int lo;
};

struct _MDSearchViewFlags {
    unsigned int selected:1;
    unsigned int selectedWithSpot:1;
    unsigned int up:1;
    unsigned int set:1;
    unsigned int updatingInternalIndex:1;
    unsigned int ignoreNextNotification:1;
    unsigned int _reserved:27;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

