//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (SPArrayExtensions)
- (id)arrayByJoiningArrays;
- (id)firstObjectOfArraysMatchingBlock:(CDUnknownBlockType)arg1;
- (id)firstObjectOfArrays;
- (void)enumerateObjectsForKeyString:(id)arg1 valueString:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (id)objectForKeyedSubscript:(id)arg1;
@end

