//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableAttributedString.h"

@interface NSMutableAttributedString (SPMutableAttributedStringExtensions)
- (void)appendImage:(id)arg1 attributes:(id)arg2;
- (void)appendImage:(id)arg1;
- (void)appendString:(id)arg1;
@end

