//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPQuery.h"

@class NSMutableArray, NSMutableDictionary, NSOperationQueue;

@interface SPAggregateQuery : SPQuery
{
    double _timeBetweenProgress;
    NSOperationQueue *_queryResponseQueue;
    double _timeOfLastResponse;
    NSMutableArray *_queryIds;
    NSMutableArray *_queries;
    NSMutableDictionary *_responses;
}

@property(retain) NSMutableDictionary *responses; // @synthesize responses=_responses;
@property(retain) NSMutableArray *queries; // @synthesize queries=_queries;
@property(retain) NSMutableArray *queryIds; // @synthesize queryIds=_queryIds;
@property double timeOfLastResponse; // @synthesize timeOfLastResponse=_timeOfLastResponse;
@property(retain) NSOperationQueue *queryResponseQueue; // @synthesize queryResponseQueue=_queryResponseQueue;
@property double timeBetweenProgress; // @synthesize timeBetweenProgress=_timeBetweenProgress;
- (void).cxx_destruct;
- (void)_processResponse:(id)arg1 toQuery:(id)arg2;
- (BOOL)_allQueriesFinished;
- (double)_soonestOfAnyCompletionTime;
- (void)setPurpose:(int)arg1;
- (int)purpose;
- (void)cancel;
- (void)start;
- (void)addQuery:(id)arg1;
- (id)initWithQuery:(id)arg1;
- (id)initWithUserQuery:(id)arg1;
- (id)initWithQueries:(id)arg1 queryString:(id)arg2;
- (void)addQueries:(id)arg1;

@end

