//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPFusedResult.h"

@class NSImage;

@interface SPAlbumResult : SPFusedResult
{
    struct __QLThumbnail *_thumbnail;
    NSImage *_albumImage;
}

+ (double)scaleFactor;
- (void).cxx_destruct;
- (BOOL)openWithSearchString:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)addAdamID:(id)arg1;
- (id)adamID;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)rank;
- (unsigned long long)score;
- (id)iconImageForApplication;
- (id)iconImage;
- (id)filePath;
- (id)card_sections;
- (id)albumImage;
- (void)dealloc;
- (id)subtitle;
- (id)title_note;
- (id)URL;
- (BOOL)shouldNotBeTopHit;
- (BOOL)isTopHitCandidate;
- (id)displayName;

@end

