//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPSliceViewController.h"

@class PRSCardSection;

@interface SPCardSectionSliceViewController : SPSliceViewController
{
    PRSCardSection *_cardSection;
}

- (void).cxx_destruct;
- (void)setUrl:(id)arg1;
- (id)url;
- (void)syncAttributes;
@property(retain, nonatomic) PRSCardSection *cardSection;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCardSection:(id)arg1 nibName:(id)arg2;

@end

