//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSView;

@interface SPCalculationSlice : NSObject
{
    NSView *_view;
    double _spacing;
    long long _attribute1;
    long long _attribute2;
}

@property long long attribute2; // @synthesize attribute2=_attribute2;
@property long long attribute1; // @synthesize attribute1=_attribute1;
@property double spacing; // @synthesize spacing=_spacing;
@property(readonly) NSView *view; // @synthesize view=_view;
- (void).cxx_destruct;
- (id)initWithView:(id)arg1;

@end

