//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSSecureCoding.h"

@class NSNumber, NSString;

@interface SPConversion : NSObject <NSCoding, NSSecureCoding>
{
    NSString *_outputUnit;
    NSNumber *_outputValue;
    NSString *_localizedOutputValue;
    NSString *_localizedOutputUnit;
    NSString *_localizedOutputValueAndUnit;
}

+ (BOOL)supportsSecureCoding;
@property(readonly) NSString *localizedOutputValueAndUnit; // @synthesize localizedOutputValueAndUnit=_localizedOutputValueAndUnit;
@property(readonly) NSString *localizedOutputUnit; // @synthesize localizedOutputUnit=_localizedOutputUnit;
@property(readonly) NSString *localizedOutputValue; // @synthesize localizedOutputValue=_localizedOutputValue;
@property(readonly) NSNumber *outputValue; // @synthesize outputValue=_outputValue;
@property(readonly) NSString *outputUnit; // @synthesize outputUnit=_outputUnit;
- (void).cxx_destruct;
- (id)category;
- (id)initWithUnit:(id)arg1 value:(id)arg2 localizedValue:(id)arg3 localizedUnit:(id)arg4 localizedOutputValueAndUnit:(id)arg5;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

