//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSTextField;

@interface SPColumnsSliceView : NSView
{
    NSTextField *_titleTextField;
}

@property NSTextField *titleTextField; // @synthesize titleTextField=_titleTextField;
- (id)columnTextFieldAtIndex:(unsigned long long)arg1;
- (unsigned long long)columnCount;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

