//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPPreviewController.h"

@class NSImageView, NSLayoutConstraint, NSTextField, NSView;

@interface SPConversionPreviewController : SPPreviewController
{
    NSTextField *_inputLabel;
    NSView *_dataFromYahoo;
    NSImageView *_conversionTypeIcon;
    NSTextField *_topResult;
    NSTextField *_resultValue1;
    NSTextField *_resultValue2;
    NSTextField *_resultValue3;
    NSTextField *_resultValue4;
    NSTextField *_resultUnit1;
    NSTextField *_resultUnit2;
    NSTextField *_resultUnit3;
    NSTextField *_resultUnit4;
    NSLayoutConstraint *_resultBlockAlignConstraint;
    NSLayoutConstraint *_separatorTopSpacingConstraint;
}

+ (id)sharedPreviewController;
@property(retain) NSLayoutConstraint *separatorTopSpacingConstraint; // @synthesize separatorTopSpacingConstraint=_separatorTopSpacingConstraint;
@property(retain) NSLayoutConstraint *resultBlockAlignConstraint; // @synthesize resultBlockAlignConstraint=_resultBlockAlignConstraint;
@property(retain) NSTextField *resultUnit4; // @synthesize resultUnit4=_resultUnit4;
@property(retain) NSTextField *resultUnit3; // @synthesize resultUnit3=_resultUnit3;
@property(retain) NSTextField *resultUnit2; // @synthesize resultUnit2=_resultUnit2;
@property(retain) NSTextField *resultUnit1; // @synthesize resultUnit1=_resultUnit1;
@property(retain) NSTextField *resultValue4; // @synthesize resultValue4=_resultValue4;
@property(retain) NSTextField *resultValue3; // @synthesize resultValue3=_resultValue3;
@property(retain) NSTextField *resultValue2; // @synthesize resultValue2=_resultValue2;
@property(retain) NSTextField *resultValue1; // @synthesize resultValue1=_resultValue1;
@property(retain) NSTextField *topResult; // @synthesize topResult=_topResult;
@property(retain) NSImageView *conversionTypeIcon; // @synthesize conversionTypeIcon=_conversionTypeIcon;
@property(retain) NSView *dataFromYahoo; // @synthesize dataFromYahoo=_dataFromYahoo;
@property(retain) NSTextField *inputLabel; // @synthesize inputLabel=_inputLabel;
- (void).cxx_destruct;
- (void)setRepresentedObject:(id)arg1;
- (void)awakeFromNib;
- (void)setupForObject:(id)arg1;
- (id)_colorizedGlyphWithName:(id)arg1;
- (id)nibName;

@end

