//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPConversionResult.h"

#import "NSCoding.h"
#import "NSSecureCoding.h"

@class NSDate;

@interface SPCurrencyConversionResult : SPConversionResult <NSCoding, NSSecureCoding>
{
    NSDate *_lastUpdated;
}

+ (BOOL)supportsSecureCoding;
@property(readonly) NSDate *lastUpdated; // @synthesize lastUpdated=_lastUpdated;
- (void).cxx_destruct;
- (id)initWithConverter:(id)arg1;
- (BOOL)isCurrency;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

