//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPResultWithSubItemsPreviewControllerViewController.h"

@class NSDateFormatter, NSObject<OS_dispatch_queue>;

@interface SPFolderPreviewController : SPResultWithSubItemsPreviewControllerViewController
{
    NSDateFormatter *_formatter;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedPreviewController;
- (void).cxx_destruct;
- (void)setupForObject:(id)arg1;
- (id)init;

@end

