//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPQuery.h"

@class NSOperationQueue, NSURL;

@interface SPImageQuery : SPQuery
{
    NSURL *_queryURL;
    NSOperationQueue *_queryResponseQueue;
}

@property(retain) NSOperationQueue *queryResponseQueue; // @synthesize queryResponseQueue=_queryResponseQueue;
@property(readonly) NSURL *queryURL; // @synthesize queryURL=_queryURL;
- (void).cxx_destruct;
- (void)cancel;
- (void)start;
- (id)initWithUserQuery:(id)arg1;
- (id)initWithQueryURL:(id)arg1;

@end

