//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextField.h"

@interface SPLevelIndicatorView : NSTextField
{
    float _floatValue;
    double _minValue;
    double _maxValue;
}

+ (id)starsAttributedStringForValue:(float)arg1 maxValue:(float)arg2;
@property double maxValue; // @synthesize maxValue=_maxValue;
@property double minValue; // @synthesize minValue=_minValue;
- (void)setFloatValue:(float)arg1;
- (float)floatValue;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

