//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@class NSURL;

@interface SPLinkButton : NSButton
{
    NSURL *_bingURL;
}

@property(retain) NSURL *bingURL; // @synthesize bingURL=_bingURL;
- (void).cxx_destruct;
- (void)mouseDown:(id)arg1;

@end

