//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPPreviewController.h"

#import "_MKPlaceViewControllerDelegate.h"

@class NSString, _MKPlaceViewController;

@interface SPLocationPreviewController : SPPreviewController <_MKPlaceViewControllerDelegate>
{
    _MKPlaceViewController *_placeViewController;
}

+ (id)sharedPreviewController;
@property(retain) _MKPlaceViewController *placeViewController; // @synthesize placeViewController=_placeViewController;
- (void).cxx_destruct;
- (BOOL)placeViewController:(id)arg1 shouldOpenHomePage:(id)arg2;
- (void)placeViewControllerDidSelectDirectionsFromAddress:(id)arg1;
- (void)placeViewControllerDidSelectDirectionsToAddress:(id)arg1;
- (id)view;
- (void)loadView;
- (void)setRepresentedObject:(id)arg1;
- (void)refresh:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

