//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPParsecQuery.h"

@interface SPParsecWebQuery : SPParsecQuery
{
}

+ (BOOL)isQuerySupported:(unsigned long long)arg1;
- (BOOL)webSearch;
- (BOOL)isParsecQuery;
- (id)groupNameForResult:(id)arg1;
- (id)categoryForResult:(id)arg1;

@end

