//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPParsecPattern : NSObject
{
    struct __MDSimpleQueryEvaluator *_queryEval;
}

- (void)dealloc;
- (BOOL)matches:(id)arg1;
- (id)initWithQuery:(id)arg1;

@end

