//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, SPGroupHeadingResult, SPResult;

@protocol SPResultViewControllerDelegate
- (void)didLoadPreviewItem:(SPResult *)arg1;
- (void)didShowPreviewItem:(SPResult *)arg1;
- (void)focusGroup:(SPGroupHeadingResult *)arg1;
- (void)revealSelectedItem;
- (void)openSelectedItem;
- (void)updateSelectingTopResult:(BOOL)arg1;
- (void)setTopHitImageForResult:(SPResult *)arg1;
- (NSString *)userQueryString;
- (unsigned long long)spotStyle;
@end

