//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSArray, NSImage, NSString, NSTextField, SPImageView;

@interface SPRichTitleSliceView : NSView
{
    NSString *_subtitleText;
    NSString *_descriptionText;
    unsigned long long _tomatoPlacement;
    NSImage *_tomatoGlyph;
    NSString *_tomatoText;
    float _ratingLevel;
    NSString *_ratingText;
    unsigned long long _moreGlyphsPlacement;
    NSArray *_moreGlyphs;
    SPImageView *_imageView;
    NSTextField *_titleTextField;
    NSTextField *_descriptionTextField;
}

@property NSTextField *descriptionTextField; // @synthesize descriptionTextField=_descriptionTextField;
@property NSTextField *titleTextField; // @synthesize titleTextField=_titleTextField;
@property SPImageView *imageView; // @synthesize imageView=_imageView;
@property(readonly) NSArray *moreGlyphs; // @synthesize moreGlyphs=_moreGlyphs;
- (void).cxx_destruct;
- (void)processChanges;
- (void)setMoreGlyphsPlacement:(unsigned long long)arg1 glyphs:(id)arg2;
@property(readonly) unsigned long long moreGlyphsPlacement;
- (void)setRatingLevel:(float)arg1 text:(id)arg2;
@property(readonly) NSString *ratingText;
@property(readonly) float ratingLevel;
- (void)setTomatoPlacement:(unsigned long long)arg1 glyph:(id)arg2 text:(id)arg3;
@property(readonly) NSString *tomatoText;
@property(readonly) NSImage *tomatoGlyph;
@property(readonly) unsigned long long tomatoPlacement;
@property(retain) NSString *descriptionText;
@property(retain) NSString *subtitleText;
@property(retain) NSString *titleText;
@property(retain) NSImage *image;
- (id)fullDescriptionAttributedString;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

