//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSColor, NSFont, NSImage, NSImageView, NSString, NSTextField;

@interface SPRowSliceView : NSView
{
    BOOL _clickable;
    NSTextField *_leadingTextField;
    NSTextField *_trailingTextField;
    NSImageView *_trailingImageView;
}

@property NSImageView *trailingImageView; // @synthesize trailingImageView=_trailingImageView;
@property NSTextField *trailingTextField; // @synthesize trailingTextField=_trailingTextField;
@property NSTextField *leadingTextField; // @synthesize leadingTextField=_leadingTextField;
@property(nonatomic) BOOL clickable; // @synthesize clickable=_clickable;
- (void)_setNoWrap:(BOOL)arg1 forTextField:(id)arg2;
- (BOOL)_getNoWrapForTextField:(id)arg1;
@property(retain, nonatomic) NSImage *trailingImage;
@property(nonatomic) BOOL trailingNoWrap;
@property(retain, nonatomic) NSColor *trailingTextColor;
@property(retain, nonatomic) NSFont *trailingFont;
@property(retain, nonatomic) NSString *trailingString;
@property(nonatomic) BOOL leadingNoWrap;
@property(retain, nonatomic) NSColor *leadingTextColor;
@property(retain, nonatomic) NSFont *leadingFont;
@property(retain, nonatomic) NSString *leadingString;
- (void)updateTrackingAreas;
- (void)cursorUpdate:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

