//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSearchFieldCell.h"

@interface SPSearchFieldCell : NSSearchFieldCell
{
}

- (id)_accessibilityUserStringValue;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (struct CGRect)cancelButtonRectForBounds:(struct CGRect)arg1;
- (id)setUpFieldEditorAttributes:(id)arg1;

@end

