//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSURL;

@interface SPSliceViewController : NSViewController
{
    double _additionalHeight;
    BOOL _underlined;
    double _viewWidth;
    NSURL *_url;
}

+ (double)defaultHeight;
@property(retain) NSURL *url; // @synthesize url=_url;
@property(getter=isUnderlined) BOOL underlined; // @synthesize underlined=_underlined;
@property double viewWidth; // @synthesize viewWidth=_viewWidth;
- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)viewClosed;
- (BOOL)handleMouseUp:(id)arg1 alternateURL:(id)arg2;
- (double)height;
- (void)setAdditionalHeight:(double)arg1;
- (double)additionalHeight;
- (void)setViewWidthFromTableView:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;

@end

