//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPStatistics : NSObject
{
    double _sum;
    double _sumOfSquares;
    unsigned long long _count;
}

@property(readonly) unsigned long long count; // @synthesize count=_count;
- (void)addObservation:(double)arg1;
@property(readonly) double standardDeviation;
@property(readonly) double variance;
@property(readonly) double average;
- (id)description;

@end

