//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPSliceViewController.h"

@class NSColor, NSFont, NSString, NSTextField, SPTextFieldSliceView;

@interface SPTextFieldSliceViewController : SPSliceViewController
{
    BOOL _noWrap;
    BOOL _hasSyncedAttributes;
    double _gapAbove;
    NSString *_stringValue;
    NSColor *_textColor;
    NSFont *_textFont;
    unsigned long long _alignment;
}

@property BOOL hasSyncedAttributes; // @synthesize hasSyncedAttributes=_hasSyncedAttributes;
@property(nonatomic) unsigned long long alignment; // @synthesize alignment=_alignment;
@property(retain, nonatomic) NSFont *textFont; // @synthesize textFont=_textFont;
@property(retain, nonatomic) NSColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) NSString *stringValue; // @synthesize stringValue=_stringValue;
@property(nonatomic) double gapAbove; // @synthesize gapAbove=_gapAbove;
@property(nonatomic) BOOL noWrap; // @synthesize noWrap=_noWrap;
- (void).cxx_destruct;
- (id)aboveConstraint;
@property(readonly) NSTextField *textField;
@property(readonly) SPTextFieldSliceView *textFieldSliceView;
- (void)syncAttributes;
- (double)height;
- (void)awakeFromNib;
- (id)initWithString:(id)arg1 font:(id)arg2 color:(id)arg3 alignment:(unsigned long long)arg4;
- (id)initWithString:(id)arg1 font:(id)arg2 color:(id)arg3;
- (id)initWithString:(id)arg1 font:(id)arg2;
- (id)initWithString:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;

@end

