//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPCardSectionSliceViewController.h"

@class NSTextField, PRSTitleCardSection, SPTitleSliceView;

@interface SPTitleSliceViewController : SPCardSectionSliceViewController
{
}

@property(readonly) NSTextField *subtitleTextField;
@property(readonly) NSTextField *titleTextField;
@property(readonly) SPTitleSliceView *titleSliceView;
- (void)syncAttributes;
- (double)height;
- (void)awakeFromNib;
@property(retain, nonatomic) PRSTitleCardSection *titleCardSection;
- (id)initWithCardSection:(id)arg1 nibName:(id)arg2;
- (id)initWithTitleCardSection:(id)arg1;

@end

