//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPParsecSimpleResult.h"

@interface SPWebResult : SPParsecSimpleResult
{
}

- (unsigned long long)rank;
- (unsigned long long)score;
- (BOOL)shouldNotBeTopHit;
- (BOOL)isTopHitCandidate;
- (BOOL)isLocalResult;
- (id)category;
- (id)groupId;

@end

