//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPPreviewController.h"

#import "QLPreviewViewDelegate.h"

@class NSProgressIndicator, NSString, NSTextField, NSView, SPWebPreviewCache, SPWebPreviewCacheItem;

@interface SPWebViewController : SPPreviewController <QLPreviewViewDelegate>
{
    SPWebPreviewCache *_cache;
    SPWebPreviewCacheItem *_currentItem;
    int _generation;
    NSView *_sitePreviewContainer;
    NSTextField *_siteName;
    NSTextField *_siteDescription;
    NSProgressIndicator *_progressView;
}

+ (id)sharedPreviewController;
@property __weak NSProgressIndicator *progressView; // @synthesize progressView=_progressView;
@property __weak NSTextField *siteDescription; // @synthesize siteDescription=_siteDescription;
@property __weak NSTextField *siteName; // @synthesize siteName=_siteName;
@property __weak NSView *sitePreviewContainer; // @synthesize sitePreviewContainer=_sitePreviewContainer;
- (void).cxx_destruct;
- (void)viewDidLayout;
- (void)viewWillLayout;
- (void)setRepresentedObject:(id)arg1;
- (void)awakeFromNib;
- (void)setupForObject:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)preheat:(id)arg1 row:(int)arg2 generation:(int)arg3;
- (void)clearPreheatCache:(int)arg1;
- (void)previewView:(id)arg1 didLoadPreviewItem:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

