//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QLPreviewViewDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, SPWebPreviewCacheItem;

@interface SPWebPreviewCache : NSObject <QLPreviewViewDelegate>
{
    int _generation;
    int _lastRow;
    id _delegate;
    NSMutableDictionary *_cachedPreviewItems;
    NSMutableArray *_reuseableCacheItems;
    NSMutableArray *_livePreviewCacheItems;
    SPWebPreviewCacheItem *_currentLoadItem;
    NSObject<OS_dispatch_queue> *_preheatQueue;
    NSObject<OS_dispatch_queue> *_submissionQueue;
}

@property int lastRow; // @synthesize lastRow=_lastRow;
@property(retain) NSObject<OS_dispatch_queue> *submissionQueue; // @synthesize submissionQueue=_submissionQueue;
@property(retain) NSObject<OS_dispatch_queue> *preheatQueue; // @synthesize preheatQueue=_preheatQueue;
@property(retain) SPWebPreviewCacheItem *currentLoadItem; // @synthesize currentLoadItem=_currentLoadItem;
@property(retain) NSMutableArray *livePreviewCacheItems; // @synthesize livePreviewCacheItems=_livePreviewCacheItems;
@property(retain) NSMutableArray *reuseableCacheItems; // @synthesize reuseableCacheItems=_reuseableCacheItems;
@property(retain) NSMutableDictionary *cachedPreviewItems; // @synthesize cachedPreviewItems=_cachedPreviewItems;
@property __weak id delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)forceLoadItem:(id)arg1;
- (id)previewForItem:(id)arg1;
- (void)previewView:(id)arg1 didLoadPreviewItem:(id)arg2;
- (void)preheat:(id)arg1 row:(int)arg2 generation:(int)arg3;
- (void)submit:(id)arg1;
- (id)cachelookup:(id)arg1;
- (void)addPreviewItem:(id)arg1;
- (void)cacheinsert:(id)arg1;
- (id)getPreviewView;
- (void)clearCache:(int)arg1 forcePreserve:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

