xcodeproj 'Flashlight.xcodeproj/'

# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "Flashlight" do

pod "Sparkle"
pod "LetsMove"
pod "GRMustache"

end

