//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAttributedString.h"

@interface NSAttributedString (SPAttributedStringExtensions)
+ (id)attributedStringWithImage:(id)arg1 attributes:(id)arg2;
+ (id)attributedStringWithImage:(id)arg1;
- (id)attributedString:(id)arg1 appendingString:(id)arg2 image:(id)arg3 attributes:(id)arg4;
- (id)attributedString:(id)arg1 appendingString:(id)arg2 image:(id)arg3;
@end

