//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (MDStringAbbreviations)
- (id)abbreviationSet;
- (id)mutableAbbreviationSet;
- (id)stringByRemovingWhitespace;
- (id)abbreviationByCamelCase;
- (id)abbreviationByWord;
- (BOOL)isCamelCaseBoundaryLocation:(unsigned long long)arg1;
- (unsigned short)baseCharacterAtIndex:(unsigned long long)arg1;
- (BOOL)hasCamelCase;
- (BOOL)hasWhitespace;
@end

