//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (SPStringExtensions)
- (void)splitIntoFirstLine:(id *)arg1 rest:(id *)arg2;
- (id)stringByReplacingRangesOfCharactersInSet:(id)arg1 withString:(id)arg2;
- (id)commonPathPrefixWithString:(id)arg1;
- (id)unquotedString;
- (id)halfQuotedString;
- (id)quotedString;
- (BOOL)isUnquoted;
- (BOOL)isHalfQuoted;
- (BOOL)isQuoted;
- (BOOL)hasInteriorSpaces;
- (BOOL)hasInteriorQuotes;
@end

