//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCopying.h"
#import "NSObject.h"
#import "PRSPredictionSupport.h"

@class NSImage, NSString, NSURL;

@protocol PRSBaseResult <NSObject, NSCopying, PRSPredictionSupport>
@property(retain, nonatomic) NSURL *section_header_more_url;
@property(retain, nonatomic) NSString *section_header_more;
@property int title_note_size;
@property(retain, nonatomic) NSString *title_note;
@property(retain, nonatomic) NSImage *completion_icon;
@property(retain, nonatomic) NSString *completion;
@property(retain, nonatomic) NSString *section_header;
@property(retain, nonatomic) NSImage *icon;
@property(retain, nonatomic) NSString *templateName;
@property(nonatomic) float resultScore;
@property(retain, nonatomic) NSString *title;
@property(retain, nonatomic) NSString *resultIdentifier;

@optional
@property(retain, nonatomic) id <PRSApp> app;
@property(retain, nonatomic) NSString *bundle_id;
@property(nonatomic) long long max_age;
@property(retain, nonatomic) NSURL *resultURL;
@property(nonatomic) long long adam_id;
@property(nonatomic) long long media_kind;
@property(retain, nonatomic) NSString *type;
@end

