//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSApplication.h"

@interface SPApplication : NSApplication
{
}

- (void)_controllerCloseMenu;
- (long long)runModalSession:(struct _NSModalSession *)arg1;
- (struct _NSModalSession *)beginModalSessionForWindow:(id)arg1;
- (void)beginSheet:(id)arg1 modalForWindow:(id)arg2 modalDelegate:(id)arg3 didEndSelector:(SEL)arg4 contextInfo:(void *)arg5;
- (long long)runModalForWindow:(id)arg1 relativeToWindow:(id)arg2;
- (long long)runModalForWindow:(id)arg1;
- (void)sendEvent:(id)arg1;
- (id)init;
- (void)watchdog;
- (void)woof;

@end

