//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextField.h"

@interface SPAppearanceTextField : NSTextField
{
    BOOL _vibrant;
}

@property BOOL vibrant; // @synthesize vibrant=_vibrant;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

