//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

/*#import "NSApplicationDelegate.h"
#import "NSWindowDelegate.h"
#import "SPResultViewControllerDelegate.h"*/

@class NSArray, NSDictionary, NSImageView, NSMutableArray, NSString, NSTimer, NSView, NSXPCConnection, NSXPCListener, SPListenerDelegate, SPQuery, SPResponse, SPResult, SPResultViewController, SPSearchField, SPSearchFieldEditor, SPSearchPanel, SPStatistics, SPStatusItemView;

@interface SPAppDelegate : NSObject <SPResultViewControllerDelegate, NSApplicationDelegate, NSWindowDelegate>
{
    BOOL _previewReady;
    BOOL _expandWhenReady;
    BOOL _showNoResultsText;
    unsigned long long _queryId;
    BOOL _locationUpdates;
    BOOL _disableReloadOfPreview;
    BOOL _amInSubView;
    BOOL _keyEvent;
    BOOL _parsecResultSelected;
    BOOL _hasVisibleReportAProblemSheet;
    BOOL _topHitIsIn;
    BOOL _queryFinished;
    BOOL _queryReadyForLaunch;
    BOOL _pendingOpen;
    BOOL _pendingReveal;
    BOOL _borderlessWindow;
    BOOL _internalIsHidingSearchWindow;
    SPResultViewController *_currentViewController;
    NSString *_userQueryString;
    SPQuery *_query;
    NSArray *_results;
    SPStatusItemView *_statusItemView;
    SPSearchPanel *_window;
    NSView *_mainView;
    unsigned long long _spotStyle;
    SPSearchFieldEditor *_searchFieldEditor;
    SPSearchField *_searchField;
    SPStatistics *_typingStatistics;
    double _lastSearchTextChangeTime;
    NSImageView *_topHitImageView;
    NSImageView *_magnifierView;
    SPResult *_topHitResult;
    // NSViewController<SPMainViewController> *_mainViewController;
    NSXPCListener *_listener;
    SPListenerDelegate *_listenerDelegate;
    NSXPCConnection *_listenerConnection;
    NSDictionary *_userQueryContentTypeDict;
    NSMutableArray *_userQueryHistory;
    SPQuery *_priorQuery;
    NSTimer *_timerForClearingQuery;
    NSTimer *_timerForUpdate;
    SPResponse *_deferredResponse;
    double _queryStartTime;
    double _lastUpdateTime;
    double _queryFinishTime;
}

+ (void)initialize;
@property BOOL internalIsHidingSearchWindow; // @synthesize internalIsHidingSearchWindow=_internalIsHidingSearchWindow;
@property double queryFinishTime; // @synthesize queryFinishTime=_queryFinishTime;
@property double lastUpdateTime; // @synthesize lastUpdateTime=_lastUpdateTime;
@property double queryStartTime; // @synthesize queryStartTime=_queryStartTime;
@property(retain) SPResponse *deferredResponse; // @synthesize deferredResponse=_deferredResponse;
@property(retain) NSTimer *timerForUpdate; // @synthesize timerForUpdate=_timerForUpdate;
@property(retain) NSTimer *timerForClearingQuery; // @synthesize timerForClearingQuery=_timerForClearingQuery;
@property(retain) SPQuery *priorQuery; // @synthesize priorQuery=_priorQuery;
@property(readonly) NSMutableArray *userQueryHistory; // @synthesize userQueryHistory=_userQueryHistory;
@property(retain) NSDictionary *userQueryContentTypeDict; // @synthesize userQueryContentTypeDict=_userQueryContentTypeDict;
@property(retain) NSXPCConnection *listenerConnection; // @synthesize listenerConnection=_listenerConnection;
@property(retain) SPListenerDelegate *listenerDelegate; // @synthesize listenerDelegate=_listenerDelegate;
@property(retain) NSXPCListener *listener; // @synthesize listener=_listener;
@property(retain) NSViewController *mainViewController; // @synthesize mainViewController=_mainViewController;
@property(retain) SPResult *topHitResult; // @synthesize topHitResult=_topHitResult;
@property __weak NSImageView *magnifierView; // @synthesize magnifierView=_magnifierView;
@property __weak NSImageView *topHitImageView; // @synthesize topHitImageView=_topHitImageView;
@property double lastSearchTextChangeTime; // @synthesize lastSearchTextChangeTime=_lastSearchTextChangeTime;
@property(readonly) SPStatistics *typingStatistics; // @synthesize typingStatistics=_typingStatistics;
@property __weak SPSearchField *searchField; // @synthesize searchField=_searchField;
@property(readonly) SPSearchFieldEditor *searchFieldEditor; // @synthesize searchFieldEditor=_searchFieldEditor;
@property(getter=isBorderlessWindow) BOOL borderlessWindow; // @synthesize borderlessWindow=_borderlessWindow;
@property(readonly) unsigned long long spotStyle; // @synthesize spotStyle=_spotStyle;
@property __weak NSView *mainView; // @synthesize mainView=_mainView;
@property __weak SPSearchPanel *window; // @synthesize window=_window;
@property(getter=isPendingReveal) BOOL pendingReveal; // @synthesize pendingReveal=_pendingReveal;
@property(getter=isPendingOpen) BOOL pendingOpen; // @synthesize pendingOpen=_pendingOpen;
@property(readonly) SPStatusItemView *statusItemView; // @synthesize statusItemView=_statusItemView;
@property(retain) NSArray *results; // @synthesize results=_results;
@property(retain) SPQuery *query; // @synthesize query=_query;
@property(readonly, getter=isQueryReadyForLaunch) BOOL queryReadyForLaunch; // @synthesize queryReadyForLaunch=_queryReadyForLaunch;
@property(readonly, getter=isQueryFinished) BOOL queryFinished; // @synthesize queryFinished=_queryFinished;
@property(readonly, getter=isTopHitIn) BOOL topHitIsIn; // @synthesize topHitIsIn=_topHitIsIn;
@property(readonly) NSString *userQueryString; // @synthesize userQueryString=_userQueryString;
@property BOOL hasVisibleReportAProblemSheet; // @synthesize hasVisibleReportAProblemSheet=_hasVisibleReportAProblemSheet;
@property BOOL parsecResultSelected; // @synthesize parsecResultSelected=_parsecResultSelected;
@property BOOL keyEvent; // @synthesize keyEvent=_keyEvent;
@property BOOL amInSubView; // @synthesize amInSubView=_amInSubView;
@property BOOL disableReloadOfPreview; // @synthesize disableReloadOfPreview=_disableReloadOfPreview;
@property(retain) SPResultViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
// - (void).cxx_destruct;
- (void)reloadPreviewForCurrentSelection;
- (void)removePreview;
- (void)doCommand:(unsigned long long)arg1;
- (void)openTargetResultWithOptions:(unsigned long long)arg1;
@property(readonly) SPResult *targetResult;
- (BOOL)openURL:(id)arg1;
- (void)openResult:(id)arg1 withOptions:(unsigned long long)arg2;
- (void)clearUserQuery;
- (void)markAsUsedFromSubItemsForResult:(id)arg1;
- (void)selectTabAtIndex:(long long)arg1;
- (void)selectTabViewItem:(id)arg1;
- (void)selectPreviousTab:(id)arg1;
- (void)selectNextTab:(id)arg1;
- (BOOL)currentSelectionIsFirstResult;
- (long long)currentSelection;
- (id)selectedResult;
- (void)dealloc;
- (void)doUserQuery:(id)arg1 options:(unsigned long long)arg2 clearResults:(BOOL)arg3;
- (void)startTimerForClearingQuery;
- (void)stopTimerForClearingQuery;
- (void)_clearQueryFromTimer:(id)arg1;
- (void)_clearSearchField;
- (void)clearResultsForEmptyQuery;
- (void)clearResultsforQueryId:(unsigned long long)arg1;
- (void)clearQuery;
- (void)processQueryResponse:(id)arg1;
- (void)updateDisplayOnTimer;
- (void)updateDisplay:(id)arg1;
- (void)hideNoResultsforQueryId:(unsigned long long)arg1 afterDelay:(double)arg2;
- (void)reloadResultsSelectingTopResult:(BOOL)arg1;
- (void)hideNoResults;
- (void)showNoResults;
- (void)setQueryFinished:(BOOL)arg1;
- (void)setQueryId:(unsigned long long)arg1;
@property(readonly) unsigned long long queryId;
- (void)performUserQuery:(id)arg1;
- (void)_performUserQuery:(id)arg1;
- (void)setUserSearchString:(id)arg1;
- (id)userSearchString;
- (void)setTopHitImageForResult:(id)arg1;
- (BOOL)isInputSourceLanguageRTL;
- (void)setSuggestionForResult:(id)arg1;
- (void)prefsChanged:(id)arg1;
- (void)doSearchWithUserQuery:(id)arg1 options:(unsigned long long)arg2;
- (void)doSearch:(id)arg1;
- (void)selectionControlInMainView;
- (void)selectionControlInSubView;
- (id)windowWillReturnFieldEditor:(id)arg1 toObject:(id)arg2;
- (void)windowDidResignKey:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)cancel:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)_statusItemView_showSearchWindow;
- (void)_statusItemView_hideSearchWindow;
- (void)showSearchWindow;
- (void)hideSearchWindow;
- (void)finishHiding;
- (void)toggleSearchWindow;
- (void)clearTopHit;
- (void)applicationDidHide:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)showPreferences:(id)arg1;
- (void)_handleOpenSearchAppleEvent:(id)arg1;
- (void)loadStatusItem;
- (BOOL)_inSimpleFinderMode;
- (void)awakeFromNib;
- (void)setupOnLaunch;
- (void)parsecSettingsDidUpdate;
- (void)_preheat;
- (void)preheat;
- (void)updateCurrentView:(id)arg1;
- (void)registerCommandKeys;
- (id)init;
- (void)updateSelectingTopResult:(BOOL)arg1;
- (void)focusGroup:(id)arg1;
- (void)revealSelectedItem;
- (void)openSelectedItem;
- (void)didShowPreviewItem:(id)arg1;
- (void)didLoadPreviewItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

