//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPQuery.h"

@class NSArray, NSString, SPMetadataPattern;

@interface SPApplicationQuery : SPQuery
{
    struct __MDAppRankEvaluator *_appRankEvaluator;
    NSArray *_rankingPatterns;
    NSString *_queryString;
    SPMetadataPattern *_queryPattern;
}

+ (id)_applicationsQueryResults;
+ (id)_applicationQueryUpdateAlternateNameForResult:(struct __MDItem *)arg1 withAttributes:(id)arg2;
+ (void)_applicationsQueryDidUpdateNotification:(id)arg1;
+ (void)_applicationsQueryDidFinishNotification:(id)arg1;
+ (void)_recreateApplicationsQuery;
+ (void)initialize;
+ (BOOL)isQuerySupported:(unsigned long long)arg1;
@property(readonly) SPMetadataPattern *queryPattern; // @synthesize queryPattern=_queryPattern;
@property(readonly) NSString *queryString; // @synthesize queryString=_queryString;
- (void).cxx_destruct;
- (void)_sendResponse:(id)arg1;
- (void)_sendFilteredResponseOfKind:(int)arg1;
- (BOOL)isCopyrightApple:(id)arg1;
- (void)setRankingQueries:(id)arg1;
- (unsigned long long)calculateScoreForResult:(id)arg1;
- (void)_applicationResultsDidUpdateNotification:(id)arg1;
- (void)_unregisterForApplicationResultsUpdateNotification;
- (void)_registerForApplicationResultsUpdateNotification;
- (BOOL)isApplicationQuery;
- (void)dealloc;
- (void)cancel;
- (void)start;
- (void)prepareQuery;

@end

