//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPPreviewController.h"

#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"

@class NSArray, NSString, NSTableView;

@interface SPAssistantPreviewController : SPPreviewController <NSTableViewDelegate, NSTableViewDataSource>
{
    NSTableView *_sliceTable;
    NSArray *_slices;
    double _extraSpace;
}

+ (id)sharedPreviewController;
@property double extraSpace; // @synthesize extraSpace=_extraSpace;
@property(retain) NSArray *slices; // @synthesize slices=_slices;
@property __weak NSTableView *sliceTable; // @synthesize sliceTable=_sliceTable;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 rowViewForRow:(long long)arg2;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)clickedInTableView:(id)arg1;
- (void)setRepresentedObject:(id)arg1;
- (void)resultDidUpdate:(id)arg1;
- (void)setupForResult:(id)arg1;
- (void)_addSlicesForSimpleResult:(id)arg1 toSliceArray:(id)arg2;
- (void)_makeAdjustmentsToLastSliceInArray:(id)arg1;
- (void)_addSlicesForCardSections:(id)arg1 toSliceArray:(id)arg2;
- (void)_addSlicesForWebCardSection:(id)arg1 toSliceArray:(id)arg2;
- (void)_addSlicesForTwitterUserCardSection:(id)arg1 toSliceArray:(id)arg2;
- (void)_addSlicesForMovieListCardSection:(id)arg1 toSliceArray:(id)arg2;
- (void)_addSlicesForMovies:(id)arg1 toSliceArray:(id)arg2;
- (void)_addSlicesForLinkTableCardSection:(id)arg1 toSliceArray:(id)arg2;
- (void)_addSlicesForTrackListCardSection:(id)arg1 toSliceArray:(id)arg2;
- (void)_addSlicesForTrailersCardSection:(id)arg1 toSliceArray:(id)arg2;
- (void)_addSlicesForRichTitleCardSection:(id)arg1 toSliceArray:(id)arg2;
- (void)_addSlicesForRowCardSection:(id)arg1 toSliceArray:(id)arg2;
- (void)_addSlicesForDescriptionCardSection:(id)arg1 toSliceArray:(id)arg2;
- (unsigned long long)normalizeImageAlignment:(unsigned long long)arg1;
- (void)_addSlicesForTitleCardSection:(id)arg1 toSliceArray:(id)arg2;
- (void)_addSliceForTextString:(id)arg1 font:(id)arg2 color:(id)arg3 alignment:(unsigned long long)arg4 gapAbove:(double)arg5 toSliceArray:(id)arg6;
- (void)_addSliceForTextString:(id)arg1 font:(id)arg2 color:(id)arg3 toSliceArray:(id)arg4;
- (void)replaceSlice:(id)arg1 withSlice:(id)arg2;
- (void)updateSliceTable;
- (void)updateSlices:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (void)viewClosed:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

