//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableRowView.h"

@interface SPBaseTableRowView : NSTableRowView
{
    BOOL _alwaysEmphasized;
}

@property(getter=isAlwaysEmphasized) BOOL alwaysEmphasized; // @synthesize alwaysEmphasized=_alwaysEmphasized;
- (BOOL)isEmphasized;
- (BOOL)allowsVibrancy;

@end

