//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPResult.h"

@class NSString;

@interface SPCalculatorResult : SPResult
{
    NSString *_inputString;
}

@property(readonly) NSString *inputString; // @synthesize inputString=_inputString;
- (void).cxx_destruct;
- (BOOL)isCalculation;
- (unsigned long long)rank;
- (unsigned long long)score;
- (id)category;
- (BOOL)isCurrency;
- (BOOL)isConversion;
- (id)initWithDisplayName:(id)arg1 inputString:(id)arg2;
- (id)pasteboardObject;
- (BOOL)openWithSearchString:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)customPreviewController;
- (unsigned long long)resultOpenOptions;
- (id)iconImage;
- (id)iconImageForApplication;

@end

