//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPCATableRowView.h"

@class NSVisualEffectView, SPDarkenView;

@interface SPCATableRowGroupView : SPCATableRowView
{
    NSVisualEffectView *_backdrop;
    SPDarkenView *_darken;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)appearanceChanged:(id)arg1;
- (BOOL)allowsVibrancy;
- (void)dealloc;

@end

