//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPCalculatorResult.h"

#import "NSCoding.h"
#import "NSSecureCoding.h"

@class NSArray, NSNumber, NSString;

@interface SPConversionResult : SPCalculatorResult <NSCoding, NSSecureCoding>
{
    NSString *_inputUnit;
    NSNumber *_inputValue;
    NSString *_localizedInputValueAndUnit;
    NSString *_conversionType;
    NSArray *_conversions;
}

+ (BOOL)supportsSecureCoding;
@property(readonly) NSArray *conversions; // @synthesize conversions=_conversions;
@property(readonly) NSString *conversionType; // @synthesize conversionType=_conversionType;
@property(readonly) NSString *localizedInputValueAndUnit; // @synthesize localizedInputValueAndUnit=_localizedInputValueAndUnit;
@property(readonly) NSNumber *inputValue; // @synthesize inputValue=_inputValue;
@property(readonly) NSString *inputUnit; // @synthesize inputUnit=_inputUnit;
- (void).cxx_destruct;
- (unsigned long long)rank;
- (unsigned long long)score;
- (BOOL)shouldNotBeTopHit;
- (BOOL)isConversion;
- (id)initWithConverter:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)customPreviewController;

@end

