//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPCardSectionSliceViewController.h"

@class PRSTextColumnsCardSection;

@interface SPColumnsSliceViewController : SPCardSectionSliceViewController
{
    long long columnCount;
}

- (id)columnTextFieldAtIndex:(unsigned long long)arg1;
- (unsigned long long)columnCount;
- (id)titleTextField;
- (id)columnsSliceView;
- (void)syncAttributes;
- (id)attributedStringForColumnSections:(id)arg1;
- (id)_attributesForWeight:(int)arg1;
- (id)_attributesForFont:(id)arg1 color:(id)arg2;
- (double)height;
- (void)awakeFromNib;
@property(retain, nonatomic) PRSTextColumnsCardSection *textColumnsCardSection;
- (id)init;
- (id)initWithCardSection:(id)arg1 nibName:(id)arg2;
- (id)initWithTextColumnsCardSection:(id)arg1;

@end

