//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPDemo : NSObject
{
}

+ (void)supplementResult:(id)arg1;
+ (id)parsecResults:(id)arg1 withQuery:(id)arg2;
+ (id)rottenTomato;
+ (id)pristineTomato;
+ (id)tomatoAtRect:(struct CGRect)arg1;
+ (id)_rottenTomatoesIconMapImage;
+ (id)movieRatingImageAtIndex:(unsigned long long)arg1;
+ (id)movieRatingImages;
+ (id)movieRatingFiles;
+ (id)tvRatingImageAtIndex:(unsigned long long)arg1;
+ (id)tvRatingImages;
+ (id)tvRatingFiles;
+ (id)morgueImageAtIndex:(unsigned long long)arg1;
+ (id)morgueImages;
+ (id)morgueFiles;
+ (id)loremWordAtIndex:(unsigned long long)arg1;
+ (id)loremWords;
+ (id)loremStringOfWordCount:(unsigned long long)arg1;
+ (id)quickStringOfRepeatCount:(unsigned long long)arg1;
+ (id)quickString;
+ (id)loremString;
+ (id)randomTomato;
+ (id)randomMovieRating;
+ (id)randomTVRating;
+ (id)randomImage;
+ (id)randomPerson;
+ (id)randomWords;
+ (id)randomWordsOfCount:(unsigned long long)arg1;
+ (id)randomWord;
+ (id)softwareResultWithQuery:(id)arg1;
+ (id)tvEpisodeResultWithQuery:(id)arg1;
+ (id)nearbyMoviesResultWithQuery:(id)arg1;
+ (id)nearbyMovieResultWithQuery:(id)arg1;
+ (id)genericSimpleResultWithQuery:(id)arg1;
+ (id)cardSectionsForMovie:(id)arg1;
+ (id)randomPlotSummary;
+ (id)randomCredits;
+ (id)randomTrailers;
+ (id)randomShowtimes;
+ (id)headerForMovie:(id)arg1;
+ (id)randomTrailerWithIndex:(int)arg1;
+ (id)randomMovieWithTitle:(id)arg1;
+ (id)albumResultWithQuery:(id)arg1;
+ (id)twitterResultWithQuery:(id)arg1;
+ (id)newsResultWithQuery:(id)arg1;
+ (id)wikiResultWithQuery:(id)arg1;

@end

