//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "NSTextViewDelegate.h"

@class NSLayoutConstraint, NSMatrix, NSString, NSTextView;

@interface SPFTEController : NSViewController <NSTextViewDelegate>
{
    NSTextView *_fteText;
    NSLayoutConstraint *_imageTextDistance;
    NSLayoutConstraint *_textHeight;
    NSMatrix *_fteImages;
}

@property(retain) NSMatrix *fteImages; // @synthesize fteImages=_fteImages;
@property(retain) NSLayoutConstraint *textHeight; // @synthesize textHeight=_textHeight;
@property(retain) NSLayoutConstraint *imageTextDistance; // @synthesize imageTextDistance=_imageTextDistance;
@property(retain) NSTextView *fteText; // @synthesize fteText=_fteText;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)textView:(id)arg1 willDisplayToolTip:(id)arg2 forCharacterAtIndex:(unsigned long long)arg3;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)adaptToDarkMode;
- (void)awakeFromNib;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

