//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@class NSLayoutConstraint, NSTextField, NSTimer, NSTrackingArea;

@interface SPGroupTableCellView : NSTableCellView
{
    NSTrackingArea *_trackingArea;
    NSTimer *_trackingTimer;
    BOOL _supportsShowAll;
    NSTextField *_myTextField;
    NSTextField *_showAll;
    NSLayoutConstraint *_showAllTrailingConstraint;
}

@property BOOL supportsShowAll; // @synthesize supportsShowAll=_supportsShowAll;
@property __weak NSLayoutConstraint *showAllTrailingConstraint; // @synthesize showAllTrailingConstraint=_showAllTrailingConstraint;
@property __weak NSTextField *showAll; // @synthesize showAll=_showAll;
@property __weak NSTextField *myTextField; // @synthesize myTextField=_myTextField;
- (void).cxx_destruct;
- (void)viewWillDraw;
- (void)prepareForReuse;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)toggleShowAll:(id)arg1;
- (void)updateTrackingAreas;
- (BOOL)mouseInView;
- (void)awakeFromNib;
- (void)appearanceChanged:(id)arg1;
- (BOOL)allowsVibrancy;
- (void)dealloc;

@end

