//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPCardSectionSliceViewController.h"

#import "NSTextViewDelegate.h"

@class NSString, PRSLinkTableCardSection;

@interface SPLinkTableSliceViewController : SPCardSectionSliceViewController <NSTextViewDelegate>
{
}

- (id)additionalHeightConstraint;
- (id)textViewMinHeightConstraint;
- (id)textView;
- (id)linkTableSliceView;
- (void)syncAttributes;
- (void)textView:(id)arg1 syncLinks:(id)arg2;
- (id)attributedStringForLinks:(id)arg1;
- (id)attributedStringForSpace;
- (id)attributedStringForLink:(id)arg1;
- (id)textAttributesForURL:(id)arg1;
- (id)textAttributes;
- (struct _NSRange)textView:(id)arg1 willChangeSelectionFromCharacterRange:(struct _NSRange)arg2 toCharacterRange:(struct _NSRange)arg3;
- (id)textView:(id)arg1 willDisplayToolTip:(id)arg2 forCharacterAtIndex:(unsigned long long)arg3;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)setAdditionalHeight:(double)arg1;
- (double)height;
- (void)awakeFromNib;
@property(retain, nonatomic) PRSLinkTableCardSection *linkTableCardSection;
- (id)init;
- (id)initWithCardSection:(id)arg1 nibName:(id)arg2;
- (id)initWithLinkTableCardSection:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

