//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PRSLogisticWithNaiveBayesEngine.h"

@class NSXPCConnection;

@interface SPLogisticWithNaiveBayesEngine : PRSLogisticWithNaiveBayesEngine
{
    NSXPCConnection *_connectionToService;
}

@property(retain) NSXPCConnection *connectionToService; // @synthesize connectionToService=_connectionToService;
- (void).cxx_destruct;
- (id)getTopHitForQuery:(id)arg1 results:(id)arg2;
- (void)updateModel;
- (void)trainModel;
- (id)initWithTrainingDBFilePath:(id)arg1 modelDBFilePath:(id)arg2;

@end

