//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPResult.h"

@class NSString, NSURL;

@interface SPMapResult : SPResult
{
    NSURL *_URL;
    NSString *_userQuery;
}

+ (BOOL)isUserQuery:(id)arg1;
@property(readonly) NSString *userQuery; // @synthesize userQuery=_userQuery;
- (void).cxx_destruct;
- (id)customPreviewController;
- (id)iconImage;
- (id)URL;
- (id)initWithUserQuery:(id)arg1;

@end

