//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, SPAppDelegate<SPResultViewControllerDelegate>, SPQuery, SPResponse, SPResult, SPResultViewController;

@protocol SPMainViewController
- (void)appDidDeactivate;
- (void)appDidBecomeActive;
- (void)markAsAbandoned:(unsigned long long)arg1;
- (void)markAsUsed:(SPResult *)arg1 query:(SPQuery *)arg2 subItem:(BOOL)arg3;
- (void)selectTabAtIndex:(long long)arg1;
- (void)selectTabViewItem:(id)arg1;
- (void)selectPreviousTab:(id)arg1;
- (void)selectNextTab:(id)arg1;
- (unsigned long long)checkForMatchingAttributes:(SPResult *)arg1 attribute:(NSString *)arg2;
- (SPResultViewController *)currentViewController;
- (void)setDelegate:(SPAppDelegate<SPResultViewControllerDelegate> *)arg1;
- (void)processQueryResponse:(SPResponse *)arg1;
@end

