//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPGroupHeadingResult.h"

@class NSString;

@interface SPMetadataGroupHeadingResult : SPGroupHeadingResult
{
    NSString *_focusString;
}

- (void).cxx_destruct;
- (void)focus:(id)arg1 result:(id)arg2;
- (BOOL)supportsFocus;
- (id)rollOverString;
- (id)initWithDisplayName:(id)arg1 focusString:(id)arg2;

@end

