//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@interface SPMoviesSliceView : NSView
{
}

- (id)subtitleTextViewMinHeightConstraintAtIndex:(unsigned long long)arg1;
- (id)subtitleTextViewAtIndex:(unsigned long long)arg1;
- (id)titleTextFieldAtIndex:(unsigned long long)arg1;
- (id)posterImageViewAtIndex:(unsigned long long)arg1;
- (unsigned long long)columnCount;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

