//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPParsecResult.h"

#import "PRSMapsResult.h"

@class MKMapItem, NSData, NSImage, NSString, NSURL;

@interface SPParsecMapsResult : SPParsecResult <PRSMapsResult>
{
    MKMapItem *location;
    NSData *protoBuf;
}

+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) NSData *protoBuf; // @synthesize protoBuf;
@property(retain, nonatomic) MKMapItem *location; // @synthesize location;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithResult:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) NSString *title_note;
- (BOOL)isMaps;
@property(retain, nonatomic) NSString *templateName;
- (id)iconImage;
@property(retain, nonatomic) NSImage *icon;
- (BOOL)openWithSearchString:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)textContent;

// Remaining properties
@property(nonatomic) long long adam_id;
@property(nonatomic) unsigned long long alternateNameMatchScore;
@property(retain, nonatomic) id <PRSApp> app;
@property(retain, nonatomic) NSString *bundle_id;
@property(retain, nonatomic) NSString *categoryForCP;
@property(retain, nonatomic) NSString *completion;
@property(retain, nonatomic) NSImage *completion_icon;
@property(nonatomic) unsigned long long contentMatchScore;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) unsigned long long displayNameMatchScore;
@property(nonatomic) BOOL doesContentMatch;
@property(nonatomic) unsigned long long engagementScore;
@property(readonly) unsigned long long hash;
@property(nonatomic) unsigned long long interestingTimeScore;
@property(nonatomic) BOOL isAlternateNameMatch;
@property(nonatomic) BOOL isDisplayNameMatch;
@property(nonatomic) BOOL isEngagedWith;
@property(nonatomic) BOOL isMostRecentlyUsed;
@property(nonatomic) BOOL isParsec;
@property(nonatomic) BOOL isParsecTopHit;
@property(nonatomic) BOOL isPredictedTopHit;
@property(nonatomic) BOOL isPremium;
@property(nonatomic) BOOL isStaticTopHit;
@property(nonatomic) BOOL isUsed;
@property(nonatomic) BOOL keyWordMatch;
@property(nonatomic) double lastUsedTime;
@property(nonatomic) long long max_age;
@property(nonatomic) long long media_kind;
@property(nonatomic) unsigned long long predicted;
@property(nonatomic) BOOL queryEverLaunched;
@property(nonatomic) unsigned long long queryIndependentScore;
@property(nonatomic) BOOL queryLastLaunched;
@property(nonatomic) unsigned long long resultEngagementScore;
@property(retain, nonatomic) NSString *resultIdentifier;
@property(nonatomic) BOOL resultLocationInteresting;
@property(nonatomic) float resultScore;
@property(retain, nonatomic) NSURL *resultURL;
@property(retain, nonatomic) NSString *section_header;
@property(retain, nonatomic) NSString *section_header_more;
@property(retain, nonatomic) NSURL *section_header_more_url;
@property(readonly) Class superclass;
@property(retain, nonatomic) NSString *title;
@property int title_note_size;
@property(nonatomic) unsigned long long topHit;
@property(retain, nonatomic) NSString *type;
@property(nonatomic) unsigned long long usedCount;

@end

