//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPResult.h"

/*#import "NSCoding.h"
#import "NSSecureCoding.h"
#import "PRSBaseResult.h"*/

@class NSImage, NSString, NSURL, SPParsecQuery;

@interface SPParsecResult : SPResult// <PRSBaseResult, NSCoding, NSSecureCoding>
{
    unsigned long long _score;
    NSString *_category;
    BOOL _hasBeenAnimated;
    int title_note_size;
    float resultScore;
    //NSString *type;
    NSString *resultIdentifier;
    //NSString *title;
    NSString *title_note;
    NSString *section_header_more;
    NSURL *section_header_more_url;
    /*unsigned long long engagementScore;
    unsigned long long queryIndependentScore;
    unsigned long long topHit;*/
    NSString *fbr;
    NSString *completion;
    NSImage *completion_icon;
    long long max_age;
    // id <PRSApp> app;
    NSString *bundle_id;
    long long adam_id;
    NSString *templateName;
    NSImage *icon;
    NSString *section_header;
    NSURL *_url;
    SPParsecQuery *_query;
    NSString *_textContent;
}

+ (id)sortedArray:(id)arg1;
+ (void)initialize;
+ (BOOL)supportsSecureCoding;
@property BOOL hasBeenAnimated; // @synthesize hasBeenAnimated=_hasBeenAnimated;
@property(readonly) NSString *textContent; // @synthesize textContent=_textContent;
@property(readonly) __weak SPParsecQuery *query; // @synthesize query=_query;
@property(retain) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *section_header; // @synthesize section_header;
@property(retain, nonatomic) NSImage *icon; // @synthesize icon;
@property(retain, nonatomic) NSString *templateName; // @synthesize templateName;
@property(nonatomic) long long adam_id; // @synthesize adam_id;
@property(retain, nonatomic) NSString *bundle_id; // @synthesize bundle_id;
// @property(retain, nonatomic) id <PRSApp> app; // @synthesize app;
@property(nonatomic) long long max_age; // @synthesize max_age;
@property(retain, nonatomic) NSImage *completion_icon; // @synthesize completion_icon;
@property(retain, nonatomic) NSString *completion; // @synthesize completion;
@property(retain, nonatomic) NSString *fbr; // @synthesize fbr;
@property(nonatomic) unsigned long long topHit; // @synthesize topHit;
@property(nonatomic) unsigned long long queryIndependentScore; // @synthesize queryIndependentScore;
@property(nonatomic) unsigned long long engagementScore; // @synthesize engagementScore;
@property(nonatomic) float resultScore; // @synthesize resultScore;
@property(retain, nonatomic) NSURL *section_header_more_url; // @synthesize section_header_more_url;
@property(retain, nonatomic) NSString *section_header_more; // @synthesize section_header_more;
@property int title_note_size; // @synthesize title_note_size;
@property(retain, nonatomic) NSString *title_note; // @synthesize title_note;
@property(retain, nonatomic) NSString *title;
@property(retain, nonatomic) NSString *resultIdentifier; // @synthesize resultIdentifier;
@property(retain, nonatomic) NSString *type;
// - (void).cxx_destruct;
- (id)thumbnail;
@property(retain, nonatomic) NSURL *resultURL;
- (BOOL)utiTypeConformsTo:(id)arg1;
- (id)rows;
- (unsigned long long)rank;
- (BOOL)isLocalResult;
- (BOOL)shouldNotBeTopHit;
- (BOOL)isTopHitCandidate;
- (unsigned long long)score;
- (void)_setQuery:(id)arg1;
- (void)_setScore:(unsigned long long)arg1;
- (void)setScore:(unsigned long long)arg1;
@property(readonly) NSString *sourceDisplayName;
- (id)groupName;
- (id)category;
@property(readonly) BOOL isLegacyWikipediaType;
@property(readonly) BOOL isTweet;
@property(readonly) BOOL isMoviesNearby;
@property(readonly) BOOL isMovieNearby;
@property(readonly) BOOL isMaps;
@property(readonly) BOOL isArtist;
@property(readonly) BOOL isTVEpisode;
@property(readonly) BOOL isSoftware;
@property(readonly) BOOL isiPadSoftware;
@property(readonly) BOOL isEbook;
@property(readonly) BOOL isSong;
@property(readonly) BOOL isMusicVideo;
@property(readonly) BOOL isFeatureFilm;
@property(readonly) BOOL isAlbum;
@property(readonly) BOOL isiTunesType;
@property(readonly) BOOL isNews;
@property(readonly) BOOL isWikipedia;
@property(readonly) BOOL isSimpleType;
- (id)URL;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)initWithQuery:(id)arg1;
- (id)displayName;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithResult:(id)arg1;
- (id)iconImageForApplication;
- (id)groupHeadingWithTitle:(id)arg1 focusString:(id)arg2;
- (id)customPreviewController;
- (id)iconImage;
// - (BOOL)openWithSearchString:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)targetString;
- (void)supplementWithResult:(id)arg1;

// Remaining properties
@property(nonatomic) unsigned long long alternateNameMatchScore;
@property(retain, nonatomic) NSString *categoryForCP;
@property(nonatomic) unsigned long long contentMatchScore;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) unsigned long long displayNameMatchScore;
@property(nonatomic) BOOL doesContentMatch;
@property(nonatomic) unsigned long long interestingTimeScore;
@property(nonatomic) BOOL isAlternateNameMatch;
@property(nonatomic) BOOL isDisplayNameMatch;
@property(nonatomic) BOOL isEngagedWith;
@property(nonatomic) BOOL isMostRecentlyUsed;
@property(nonatomic) BOOL isParsec;
@property(nonatomic) BOOL isParsecTopHit;
@property(nonatomic) BOOL isPredictedTopHit;
@property(nonatomic) BOOL isPremium;
@property(nonatomic) BOOL isStaticTopHit;
@property(nonatomic) BOOL isUsed;
@property(nonatomic) BOOL keyWordMatch;
@property(nonatomic) double lastUsedTime;
@property(nonatomic) long long media_kind;
@property(nonatomic) unsigned long long predicted;
@property(nonatomic) BOOL queryEverLaunched;
@property(nonatomic) BOOL queryLastLaunched;
@property(nonatomic) unsigned long long resultEngagementScore;
@property(nonatomic) BOOL resultLocationInteresting;
@property(readonly) Class superclass;
@property(nonatomic) unsigned long long usedCount;

@end

