//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPPattern : NSObject
{
}

- (BOOL)matches:(id)arg1;
- (id)mutableFilterResults:(id)arg1;
- (id)filterResults:(id)arg1;

@end

