//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPQuery.h"

@class NSArray, NSObject<OS_dispatch_queue>, NSString;

@interface SPParsecQuery : SPQuery
{
    NSArray *_rankingPatterns;
    double _scaleFactor;
    NSObject<OS_dispatch_queue> *_queue;
    NSString *_shortcutUserQueryString;
    double _timeout;
    long long _queryTaskId;
}

+ (void)deactivate;
+ (void)activate;
+ (void)killFeedback;
+ (void)flushFeedback;
+ (void)addFeedback:(id)arg1;
+ (BOOL)isQuerySupported:(unsigned long long)arg1;
+ (BOOL)isLocaleSupported;
+ (void)initialize;
@property long long queryTaskId; // @synthesize queryTaskId=_queryTaskId;
@property double timeout; // @synthesize timeout=_timeout;
@property(retain) NSString *shortcutUserQueryString; // @synthesize shortcutUserQueryString=_shortcutUserQueryString;
- (void).cxx_destruct;
- (double)scaleFactor;
- (unsigned long long)calculateScoreForResult:(id)arg1;
- (void)setRankingQueries:(id)arg1;
- (id)groupNameForResult:(id)arg1;
- (id)categoryForResult:(id)arg1;
- (BOOL)vetURLForResult:(id)arg1;
- (void)_setupTimeout;
- (BOOL)supportsRefinement;
- (BOOL)isParsecQuery;
- (BOOL)isRemoteQuery;
- (void)cancel;
- (void)start;
- (void)queryDidFinish:(long long)arg1 fbq:(id)arg2 results:(id)arg3;
- (void)dealloc;
- (id)initWithUserQuery:(id)arg1 options:(unsigned long long)arg2;
- (BOOL)webSearch;

@end

