//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSViewController.h"

@class SPResult;
#import <AppKit/AppKit.h>

@interface SPPreviewController : NSViewController
{
    SPResult *_internalPreviewResult;
}

@property(retain) SPResult *internalPreviewResult; // @synthesize internalPreviewResult=_internalPreviewResult;
//- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)mouseUp:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)show;
- (void)hide;
- (void)clearPreheatCache:(int)arg1;
- (void)preheat:(id)arg1 row:(int)arg2 generation:(int)arg3;

@end

