//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSEnumerator.h"

@class NSMutableArray;

@interface SPPriorityQueue : NSEnumerator
{
    NSMutableArray *_heap;
    CDUnknownBlockType _comparator;
}

@property(readonly) CDUnknownBlockType comparator; // @synthesize comparator=_comparator;
- (void).cxx_destruct;
- (void)_swim:(unsigned long long)arg1;
- (void)_sink:(unsigned long long)arg1;
- (void)_removeFirstObject;
- (id)_firstObject;
- (id)description;
- (id)copy;
- (void)removeAllObjects;
- (void)addObject:(id)arg1;
- (id)nextObject;
- (unsigned long long)count;
- (id)initWithComparator:(CDUnknownBlockType)arg1;
- (void)addObjectsFromSet:(id)arg1;
- (void)addObjectsFromArray:(id)arg1;
- (id)reverseObjectEnumerator;
- (id)initWithSortDescriptors:(id)arg1;

@end

