//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPPreviewController.h"

@class NSProgressIndicator;

@interface SPQLThumbnailPreviewController : SPPreviewController
{
    struct __QLThumbnail *_thumbnail;
    NSProgressIndicator *_spinner;
}

+ (id)sharedPreviewController;
@property __weak NSProgressIndicator *spinner; // @synthesize spinner=_spinner;
- (void).cxx_destruct;
- (void)setRepresentedObject:(id)arg1;
- (void)awakeFromNib;
- (void)setupForObject:(id)arg1 icon:(BOOL)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

