//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

// #import "NSObject.h"

@class NSArray, NSMutableArray, NSString, SPResponse;

typedef void (^SPQueryResponseHandler)(SPResponse* response);

@interface SPQuery : NSObject
{
    NSMutableArray *_childQueries;
    double _startTime;
    int _purpose;
    int _queryState;
    unsigned long long _queryOptions;
    unsigned long long _queryId;
    NSString *_userQueryString;
    unsigned long long _startOrderIndex;
    __weak SPQuery *_parentQuery;
    double _queryStartTime;
    SPQueryResponseHandler _clientResponseHandler;
    NSString *_internalUnmodifiedUserQueryString;
}

+ (void)_resetStatisticsForKey:(id)arg1;
+ (void)_resetStatistics;
+ (void)_dumpStatistics;
+ (BOOL)isQuerySupported:(unsigned long long)arg1;
+ (void)initialize;
@property(retain) NSString *internalUnmodifiedUserQueryString; // @synthesize internalUnmodifiedUserQueryString=_internalUnmodifiedUserQueryString;
@property(copy) SPQueryResponseHandler clientResponseHandler; // @synthesize clientResponseHandler=_clientResponseHandler;
@property int queryState; // @synthesize queryState=_queryState;
@property double queryStartTime; // @synthesize queryStartTime=_queryStartTime;
@property __weak SPQuery *parentQuery; // @synthesize parentQuery=_parentQuery;
@property int purpose; // @synthesize purpose=_purpose;
@property unsigned long long startOrderIndex; // @synthesize startOrderIndex=_startOrderIndex;
@property(readonly) NSString *userQueryString; // @synthesize userQueryString=_userQueryString;
@property(readonly) unsigned long long queryId; // @synthesize queryId=_queryId;
@property unsigned long long queryOptions; // @synthesize queryOptions=_queryOptions;
@property(readonly, getter=isDictionaryQuery) BOOL dictionaryQuery;
@property(readonly) BOOL supportsRefinement;
@property(readonly, getter=isCalculatorQuery) BOOL calculatorQuery;
@property(readonly, getter=isApplicationQuery) BOOL applicationQuery;
@property(readonly, getter=isDocumentQuery) BOOL documentQuery;
@property(readonly, getter=isRemoteQuery) BOOL remoteQuery;
@property(readonly, getter=isParsecQuery) BOOL parsecQuery;
- (double)_completionTimeForStandardDeviationMultiple:(double)arg1 defaultElapsedTime:(double)arg2;
- (void)_queryDidComplete;
- (void)_queryWillStart;
- (double)latestCompletionTime;
- (double)expectedCompletionTime;
- (double)soonestCompletionTime;
- (double)startTime;
- (id)statisticsKey;
- (void)cancel;
- (void)start;
- (BOOL)isFinished;
- (BOOL)isCanceled;
- (BOOL)isCompleted;
- (BOOL)isStarted;
- (void)addChildQuery:(id)arg1;
@property(readonly) NSArray *childQueries;
@property(copy) SPQueryResponseHandler responseHandler;
@property(retain) NSString *unmodifiedUserQueryString;
- (id)description;
- (BOOL)updateUserQueryString:(id)arg1;
- (id)initWithUserQuery:(id)arg1 options:(unsigned long long)arg2;
- (id)initWithUserQuery:(id)arg1;
- (void)startWithResponseHandler:(SPQueryResponseHandler)arg1;

@end

