//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPPreviewController.h"

@class NSArray, NSString, SPResultWithSubitemsHelper, SPResultWithoutSubitemsHelper;

@interface SPResultWithSubItemsPreviewControllerViewController : SPPreviewController
{
    BOOL _awoke;
    NSArray *_subItems;
    NSString *_secondaryString;
    NSString *_filePath;
    NSString *_displayName;
    SPResultWithSubitemsHelper *_itemWithSubItemHelper;
    SPResultWithoutSubitemsHelper *_itemWithoutSubItemHelper;
}

+ (id)sharedPreviewController;
@property(retain) SPResultWithoutSubitemsHelper *itemWithoutSubItemHelper; // @synthesize itemWithoutSubItemHelper=_itemWithoutSubItemHelper;
@property(retain) SPResultWithSubitemsHelper *itemWithSubItemHelper; // @synthesize itemWithSubItemHelper=_itemWithSubItemHelper;
@property(retain) NSString *displayName; // @synthesize displayName=_displayName;
@property(retain) NSString *filePath; // @synthesize filePath=_filePath;
@property(retain) NSString *secondaryString; // @synthesize secondaryString=_secondaryString;
@property(retain) NSArray *subItems; // @synthesize subItems=_subItems;
- (void).cxx_destruct;
- (void)openItem:(BOOL)arg1;
- (void)setRepresentedObject:(id)arg1;
- (void)awakeFromNib;
- (void)doubleClick:(id)arg1;
- (void)setupForObject:(id)arg1;
- (id)icon;
- (id)init;

@end

