//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@class SPAppearanceTextField;

@interface SPResultTableCellView : NSTableCellView
{
    SPAppearanceTextField *_myTextField;
    SPAppearanceTextField *_titleNote;
}

@property __weak SPAppearanceTextField *titleNote; // @synthesize titleNote=_titleNote;
@property __weak SPAppearanceTextField *myTextField; // @synthesize myTextField=_myTextField;
- (void).cxx_destruct;
- (BOOL)allowsVibrancy;
- (void)setBackgroundStyle:(long long)arg1;
- (void)awakeFromNib;
- (void)appearanceChanged:(id)arg1;
- (void)dealloc;

@end

