//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSViewController;
// #import "NSViewController.h"
#import "SPResultViewControllerDelegate-Protocol.h"

@class NSArray, NSButton, NSString;

@interface SPResultViewController : NSViewController
{
    BOOL _awoke;
    id <SPResultViewControllerDelegate> _delegate;
    NSArray *_results;
    NSString *_name;
    NSButton *_theButton;
}

@property(retain) NSButton *theButton; // @synthesize theButton=_theButton;
@property BOOL awoke; // @synthesize awoke=_awoke;
@property(retain) NSString *name; // @synthesize name=_name;
@property(retain) NSArray *results; // @synthesize results=_results;
@property __weak id <SPResultViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)doCommand:(unsigned long long)arg1;
- (void)removePreview;
- (void)hideNoResults;
- (void)showNoResults;
- (void)reloadResultsSelectingTopResult:(BOOL)arg1 animate:(BOOL)arg2;
- (void)selectTopResultIfNotSelected;
- (void)doubleClick:(id)arg1;
- (BOOL)updateViewForSelectedResult:(id)arg1;
- (BOOL)reloadPreviewForCurrentSelection;
- (void)clearPreview;
- (id)selectedResult;
- (long long)numberOfItems;
- (BOOL)currentSelectionIsFirstResult;
- (long long)currentSelection;
- (id)resultsView;
- (void)adjustSubviews;
- (void)awakeFromNib;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 name:(id)arg3;

@end

