//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSArray, NSDictionary, NSError, NSString;

@interface SPResponse : NSObject
{
    BOOL _topHitIsIn;
    BOOL _noChangeInResultsSinceLastResponse;
    BOOL _parsecFinished;
    BOOL _metadataFinished;
    int _kind;
    NSError *_error;
    NSArray *_results;
    NSDictionary *_groupedResults;
    NSString *_fbq;
    NSString *_userQueryString;
    NSArray *_added;
    NSArray *_changed;
    NSArray *_removed;
}

@property(readonly) NSArray *removed; // @synthesize removed=_removed;
@property(readonly) NSArray *changed; // @synthesize changed=_changed;
@property(readonly) NSArray *added; // @synthesize added=_added;
@property(retain) NSString *userQueryString; // @synthesize userQueryString=_userQueryString;
@property(retain) NSString *fbq; // @synthesize fbq=_fbq;
@property BOOL metadataFinished; // @synthesize metadataFinished=_metadataFinished;
@property BOOL parsecFinished; // @synthesize parsecFinished=_parsecFinished;
@property BOOL noChangeInResultsSinceLastResponse; // @synthesize noChangeInResultsSinceLastResponse=_noChangeInResultsSinceLastResponse;
@property BOOL topHitIsIn; // @synthesize topHitIsIn=_topHitIsIn;
@property(readonly) NSDictionary *groupedResults; // @synthesize groupedResults=_groupedResults;
@property(readonly) NSArray *results; // @synthesize results=_results;
@property(readonly) NSError *error; // @synthesize error=_error;
@property(readonly) int kind; // @synthesize kind=_kind;
// - (void).cxx_destruct;
- (id)responseFilteredWithPattern:(id)arg1;
- (id)description;
- (id)initWithError:(id)arg1;
- (id)initWithResults:(id)arg1;
- (id)initWithKind:(int)arg1 results:(id)arg2;
- (id)initWithKind:(int)arg1 results:(id)arg2 groupedResults:(id)arg3;
- (id)initWithKind:(int)arg1 results:(id)arg2 groupedResults:(id)arg3 error:(id)arg4;

@end

