//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPCardSectionSliceViewController.h"

@class PRSRichTitleCardSection;

@interface SPRichTitleSliceViewController : SPCardSectionSliceViewController
{
}

- (id)richTitleSliceView;
- (void)syncAttributes;
- (double)height;
- (void)awakeFromNib;
@property(retain, nonatomic) PRSRichTitleCardSection *richTitleCardSection;
- (id)initWithCardSection:(id)arg1 nibName:(id)arg2;
- (id)initWithRichTitleCardSection:(id)arg1;

@end

