//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPSliceViewController.h"

@class PRSRowCardSection;

@interface SPRowSliceViewController : SPSliceViewController
{
    PRSRowCardSection *_rowCardSection;
}

- (void).cxx_destruct;
- (id)rowSliceView;
- (void)syncAttributes;
@property(retain, nonatomic) PRSRowCardSection *rowCardSection;
- (double)height;
- (void)awakeFromNib;
- (id)initWithRowCardSection:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

