//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSearchField.h"

#import "NSTextViewDelegate.h"

@class NSString;

@interface SPSearchField : NSSearchField <NSTextViewDelegate>
{
}

- (BOOL)textView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (struct _NSRange)textView:(id)arg1 willChangeSelectionFromCharacterRange:(struct _NSRange)arg2 toCharacterRange:(struct _NSRange)arg3;
@property(readonly) NSString *targetStringValue;
- (id)tabCompletionStringValue;
@property(readonly) NSString *completionStringValue;
@property(retain) NSString *userStringValue;
@property(readonly) NSString *selectedStringValue;
@property(readonly) struct _NSRange targetRange;
@property(readonly) struct _NSRange completionRange;
@property(readonly) struct _NSRange userRange;
@property(readonly) struct _NSRange selectedRange;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)allowsVibrancy;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

