//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPPattern.h"

@class NSString;

@interface SPShortcutPattern : SPPattern
{
    NSString *_displayName;
    NSString *_filePath;
}

@property(readonly) NSString *filePath; // @synthesize filePath=_filePath;
@property(readonly) NSString *displayName; // @synthesize displayName=_displayName;
- (void).cxx_destruct;
- (BOOL)matches:(id)arg1;
- (id)initWithDisplayName:(id)arg1 filePath:(id)arg2;

@end

