//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPParsecSimpleResult.h"

@class NSString;

@interface SPShowAllInFinderResult : SPParsecSimpleResult
{
    NSString *_userQuery;
}

- (void).cxx_destruct;
- (BOOL)allowsCPRecording;
- (BOOL)open;
- (BOOL)openWithSearchString:(id)arg1 block:(CDUnknownBlockType)arg2;
- (BOOL)isShowAllInFinderResult;
- (id)icon;
- (id)initWithUserQuery:(id)arg1;

@end

