//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPPreviewResultController.h"

#import "SPMainViewController.h"

@class NSObject<OS_dispatch_queue>, NSTimer, PRSRenderFeedback, SPIndexingProgressResult;

@interface SPSidewaysMainViewController : SPPreviewResultController <SPMainViewController>
{
    unsigned long long _mtflags;
    BOOL _registeredForServerDeath;
    float _indexingPercentage;
    SPIndexingProgressResult *_indexingResult;
    NSTimer *_feedbackTimer;
    NSObject<OS_dispatch_queue> *_backgroundQueue;
    PRSRenderFeedback *_renderFeedback;
}

+ (void)initialize;
@property(retain) PRSRenderFeedback *renderFeedback; // @synthesize renderFeedback=_renderFeedback;
@property(retain) NSObject<OS_dispatch_queue> *backgroundQueue; // @synthesize backgroundQueue=_backgroundQueue;
@property(retain) NSTimer *feedbackTimer; // @synthesize feedbackTimer=_feedbackTimer;
@property(retain) SPIndexingProgressResult *indexingResult; // @synthesize indexingResult=_indexingResult;
@property float indexingPercentage; // @synthesize indexingPercentage=_indexingPercentage;
- (void).cxx_destruct;
- (void)indexUpdate:(id)arg1;
- (BOOL)updateViewForSelectedResult:(id)arg1;
- (void)sendFeedback:(id)arg1;
- (void)updateResultWithFeaturesForPredictionEngine:(id)arg1;
- (unsigned long long)valueForTime;
- (void)markAsUsed:(id)arg1 query:(id)arg2 subItem:(BOOL)arg3;
- (void)deleteOldShortcuts;
- (void)engage:(id)arg1 preview:(BOOL)arg2;
- (void)markAsEngaged:(id)arg1 query:(id)arg2 timestamp:(double)arg3 preview:(BOOL)arg4;
- (void)logFeatureSet:(id)arg1;
- (unsigned long long)checkForMatchingAttributes:(id)arg1 attribute:(id)arg2;
- (void)markAsAbandoned:(unsigned long long)arg1;
- (void)appDidBecomeActive;
- (void)appDidDeactivate;
- (void)reloadResultsSelectingTopResult:(BOOL)arg1 animate:(BOOL)arg2;
- (void)selectTabAtIndex:(long long)arg1;
- (void)selectTabViewItem:(id)arg1;
- (void)selectPreviousTab:(id)arg1;
- (void)selectNextTab:(id)arg1;
- (id)rankAndPrune:(id)arg1 maxResults:(unsigned long long)arg2 parsecResultCategories:(id)arg3 topHitCategory:(id)arg4;
- (id)currentViewController;
- (void)processQueryResponse:(id)arg1;
- (void)logQueriesForCorePrediction:(id)arg1 results:(id)arg2 used:(BOOL)arg3 engaged:(BOOL)arg4;
- (void)appendParsecSlice:(id)arg1 name:(id)arg2 results:(id)arg3 topHit:(id)arg4;
- (void)addResultsForGroup:(id)arg1 title:(id)arg2 topHit:(id)arg3 toArray:(id)arg4 focusString:(id)arg5;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

