//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPSliceViewController.h"

@interface SPSpacerSliceViewController : SPSliceViewController
{
    double _internalHeight;
}

@property double internalHeight; // @synthesize internalHeight=_internalHeight;
- (double)height;
- (id)initWithHeight:(double)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

