//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSTextField;

@interface SPTitleSliceView : NSView
{
    NSTextField *_titleTextField;
    NSTextField *_subtitleTextField;
}

@property NSTextField *subtitleTextField; // @synthesize subtitleTextField=_subtitleTextField;
@property NSTextField *titleTextField; // @synthesize titleTextField=_titleTextField;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

