//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSButton, NSLayoutConstraint, NSTextField, SPImageView;

@interface SPTrailersSliceView : NSView
{
    NSTextField *_titleTextField;
    unsigned long long _numberOfTrailers;
    SPImageView *_trailerImageView1;
    SPImageView *_trailerImageView2;
    SPImageView *_trailerImageView3;
    NSLayoutConstraint *_trailerImageViewHeightConstraint;
    NSTextField *_trailerTextField1;
    NSTextField *_trailerTextField2;
    NSTextField *_trailerTextField3;
    NSButton *_playButton;
    long long _hoverTrailerIndex;
}

@property long long hoverTrailerIndex; // @synthesize hoverTrailerIndex=_hoverTrailerIndex;
@property NSButton *playButton; // @synthesize playButton=_playButton;
@property NSTextField *trailerTextField3; // @synthesize trailerTextField3=_trailerTextField3;
@property NSTextField *trailerTextField2; // @synthesize trailerTextField2=_trailerTextField2;
@property NSTextField *trailerTextField1; // @synthesize trailerTextField1=_trailerTextField1;
@property NSLayoutConstraint *trailerImageViewHeightConstraint; // @synthesize trailerImageViewHeightConstraint=_trailerImageViewHeightConstraint;
@property SPImageView *trailerImageView3; // @synthesize trailerImageView3=_trailerImageView3;
@property SPImageView *trailerImageView2; // @synthesize trailerImageView2=_trailerImageView2;
@property SPImageView *trailerImageView1; // @synthesize trailerImageView1=_trailerImageView1;
@property unsigned long long numberOfTrailers; // @synthesize numberOfTrailers=_numberOfTrailers;
@property NSTextField *titleTextField; // @synthesize titleTextField=_titleTextField;
- (void)dealloc;
- (void)cursorUpdate:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updatePlayButton;
- (BOOL)_isValidTrailerIndex:(long long)arg1;
- (long long)_indexForTrackingAreaEvent:(id)arg1;
- (void)updateTrackingAreas;
- (void)_removeTrackingAreas;
- (void)mouseUp:(id)arg1;
- (void)_sendAction:(SEL)arg1 to:(id)arg2 from:(id)arg3;
- (id)trailerTextFieldAtIndex:(unsigned long long)arg1;
- (id)trailerImageViewAtIndex:(unsigned long long)arg1;
@property(readonly) unsigned long long maximumNumberOfTrailers;
- (void)awakeFromNib;

@end

