//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPSliceViewController.h"

#import "NSSoundDelegate.h"

@class NSSound, NSString, PRSTrack;

@interface SPTrackSliceViewController : SPSliceViewController <NSSoundDelegate>
{
    PRSTrack *_track;
    NSSound *_playingSound;
}

+ (void)initialize;
@property(retain) NSSound *playingSound; // @synthesize playingSound=_playingSound;
@property(readonly) PRSTrack *track; // @synthesize track=_track;
- (void).cxx_destruct;
- (void)sound:(id)arg1 didFinishPlaying:(BOOL)arg2;
- (void)viewClosed;
- (void)togglePlaying:(id)arg1;
- (void)startedPlaying:(id)arg1;
- (id)trackSliceView;
- (void)syncAttributes;
- (void)setAdditionalHeight:(double)arg1;
- (double)height;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithTrack:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

