//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPCardSectionSliceViewController.h"

@class PRSTwitterUserCardSection;

@interface SPTwitterUserSliceViewController : SPCardSectionSliceViewController
{
}

- (id)subtitleTextField;
- (id)titleTextField;
- (id)imageView;
- (id)twitterUserSliceView;
- (void)syncAttributes;
- (double)height;
- (void)awakeFromNib;
@property(retain, nonatomic) PRSTwitterUserCardSection *twitterUserCardSection;
- (id)init;
- (id)initWithCardSection:(id)arg1 nibName:(id)arg2;
- (id)initWithTwitterUserCardSection:(id)arg1;

@end

