//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPSliceViewController.h"

@class NSArray, NSImageView, NSLayoutConstraint, NSTextField;

@interface SPWebSliceController : SPSliceViewController
{
    NSImageView *_siteIcon;
    NSTextField *_siteName;
    NSTextField *_siteDomain;
    NSLayoutConstraint *_siteDomainBaseToSiteNameBase;
    NSLayoutConstraint *_siteDomainBaseToBottomConstraint;
    NSArray *_siteIconConstraints;
    NSLayoutConstraint *_siteNameBaseToBottom;
}

@property(retain) NSLayoutConstraint *siteNameBaseToBottom; // @synthesize siteNameBaseToBottom=_siteNameBaseToBottom;
@property(retain) NSArray *siteIconConstraints; // @synthesize siteIconConstraints=_siteIconConstraints;
@property __weak NSLayoutConstraint *siteDomainBaseToBottomConstraint; // @synthesize siteDomainBaseToBottomConstraint=_siteDomainBaseToBottomConstraint;
@property __weak NSLayoutConstraint *siteDomainBaseToSiteNameBase; // @synthesize siteDomainBaseToSiteNameBase=_siteDomainBaseToSiteNameBase;
@property __weak NSTextField *siteDomain; // @synthesize siteDomain=_siteDomain;
@property __weak NSTextField *siteName; // @synthesize siteName=_siteName;
@property __weak NSImageView *siteIcon; // @synthesize siteIcon=_siteIcon;
- (void).cxx_destruct;
- (double)height;
- (void)setViewWidth:(double)arg1;
- (void)setRepresentedObject:(id)arg1;
- (void)awakeFromNib;
- (void)setupForObject:(id)arg1;
- (void)_setConstraintsForSiteIconOfSize:(struct CGSize)arg1;
- (id)initWithCardSection:(id)arg1;

@end

