//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class QLPreviewView, SPResult;

@interface SPWebPreviewCacheItem : NSObject
{
    int _row;
    int _generation;
    QLPreviewView *_previewView;
    SPResult *_result;
}

@property int generation; // @synthesize generation=_generation;
@property int row; // @synthesize row=_row;
@property(retain) SPResult *result; // @synthesize result=_result;
@property(retain) QLPreviewView *previewView; // @synthesize previewView=_previewView;
- (void).cxx_destruct;
- (void)dealloc;
- (id)description;

@end

